### PR TITLE
Fix issues identified by automated audit

### LINKED ISSUE #33: Recommended changes resulting from automated audit
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [x] You are currently referencing Cake.Core 0.30.0. Please upgrade to 0.33.0
- [ ] The nuget package for your addin should use the cake-contrib icon. Specifically, your addin's `.csproj` should have a line like this: `<PackageIconUrl>https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/cake-contrib-medium.png</PackageIconUrl>`.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.

This issue was created by a tool: Cake.AddinDiscoverer version 3.12.1

### PR DESCRIPTION
**Pull request by Jericho**
This pull request was created by a tool: Cake.AddinDiscoverer version 3.14.0

Resolves #33

### CODE REVIEW

**Comment by ecampidoglio** [comment]
This PR isn't solving any real issue, so I'm going to close it. Feel free to reopen, if you want to discuss it further.

**Comment by gep13** [comment]
This PR was created to move away from using `rawgit.com` which is closing down its service.  While the iconUrl may still work just now, it isn't going to work long term.  The now suggestion is to use an alternative CDN for the icon, which is what this PR is addressing.

**Comment by gep13** [comment]
@ecampidoglio have a look here for more information about rawgit closing down: https://rawgit.com/

**Comment by ecampidoglio** [comment]
@gep13 Well, this changes things. I'll update the package URL. 👍

**Pull request closed without merging**
